#!/bin/bash
# mp3のID3タグを全部消す。文字化けするから

#IFS環境変数をバックアップ
IFS_BACKUP=$IFS
#IFSを改行区切りにする
IFS=$'\n'

count1=$(ls|grep mp3|wc -l)

for i in `seq 1 $count1`
do
    name=$(ls|grep mp3|head -$i|tail -1)
    eyeD3 --remove-all --to-v2.4 --set-encoding=utf16-BE -a "" -A "" -t "$name" $name

    echo "$name"
done

#IFSを元に戻す
IFS=$IFS_BACKUP
echo $str
